- name: checking webserver status
  hosts: web*
  tasks:
  - name: checking apache status
    service: name="{{ item }}" state=started
    with_items:
    - viewweb
    - slweb
    
- name: chekcing haproxy status
  hosts: haproxy*
  tasks:
  - name: checking haproxy status
    service: name=haproxy state=started
  tasks:
  - name: checking keepalived status
    service: name=keepalived state=started
    
- name: checking database status
  hosts: viewdb*,slsdb*
  tasks:
  - name: checking database status
    shell: pcs status

- name: checking samba status
  hosts: smaba
  tasks:
  - name: checking database status
    service: name=smb state=started
