- name: checking webserver status
  hosts: web*
  tasks:
  - name: checking apache status
    service: name="{{ item }}" state=started
    with_items:
    - viewweb
    - slweb
    register: result
  - debug: var: result.stdout_lines
    
- name: chekcing haproxy status
  hosts: haproxy*
  tasks:
  - name: checking haproxy status
    service: name=haproxy state=started
    register: result
  - debug: var: result.stdout_lines
  tasks:
  - name: checking keepalived status
    service: name=keepalived state=started
    register: result
  - debug: var: result.stdout_lines
    
- name: checking database status
  hosts: viewdb*,slsdb*
  tasks:
  - name: checking database status
    pacemaker_cluster:
      state: online
    register: result
  - debug: var: result.stdout_lines

- name: checking samba status
  hosts: samba
  tasks:
  - name: checking database status
    service: name=smb state=started
    register: result
  - debug: var: result.stdout_lines
