- name: checking webserver status
  hosts: web*
  tasks:
  - name: checking apache status
    shell: systemctl status "{{ item }}"
    with_items:
    - viewweb
    - slweb
    register: result
  - name: show report
    debug:
      var: result
